import type {
  AttributeKey,
  AttributesStore,
  MuscleMapStore,
  ProfileStore,
  WorkoutsStore,
  AchievementsStore,
  AthleteProfileStore,
} from './types'

export const ALL_ATTRIBUTES: AttributeKey[] = [
  'chest', 'shoulders', 'back', 'legs', 'arms', 'core', 'cardio',
]

export const ATTRIBUTE_LABELS: Record<AttributeKey, string> = {
  chest: '胸',
  shoulders: '肩',
  back: '背',
  legs: '腿',
  arms: '手臂',
  core: '核心',
  cardio: '心肺',
}

export function defaultWorkoutsStore(): WorkoutsStore {
  return { version: 1, items: [] }
}

export function defaultAttributesStore(): AttributesStore {
  const items = {} as Record<AttributeKey, { level: number; xp: number; totalXp: number; lastChangedAt: null }>
  for (const key of ALL_ATTRIBUTES) {
    items[key] = { level: 1, xp: 0, totalXp: 0, lastChangedAt: null }
  }
  return { version: 1, items, lastWorkoutIdApplied: null }
}

export function defaultMuscleMapStore(): MuscleMapStore {
  return {
    version: 1,
    items: [
      {
        exerciseName: '卧推',
        aliases: ['杠铃卧推', '哑铃卧推', 'bench press'],
        type: 'strength',
        primary: ['chest'],
        secondary: ['arms', 'shoulders'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '深蹲',
        aliases: ['杠铃深蹲', '哑铃深蹲', 'squat'],
        type: 'strength',
        primary: ['legs'],
        secondary: ['core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '引体向上',
        aliases: ['pullup', 'pull-up', 'chin-up'],
        type: 'strength',
        primary: ['back'],
        secondary: ['arms'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '硬拉',
        aliases: ['罗马尼亚硬拉', 'deadlift'],
        type: 'strength',
        primary: ['back', 'legs'],
        secondary: ['core', 'arms'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '推举',
        aliases: ['肩推', '哑铃肩推', 'overhead press', 'OHP'],
        type: 'strength',
        primary: ['shoulders'],
        secondary: ['arms', 'core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '侧平举',
        aliases: ['lateral raise'],
        type: 'strength',
        primary: ['shoulders'],
        secondary: [],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '弯举',
        aliases: ['二头弯举', '哑铃弯举', 'bicep curl'],
        type: 'strength',
        primary: ['arms'],
        secondary: [],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '臂屈伸',
        aliases: ['tricep dip', 'tricep extension'],
        type: 'strength',
        primary: ['arms'],
        secondary: ['chest'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '俯卧撑',
        aliases: ['push-up', 'pushup'],
        type: 'strength',
        primary: ['chest'],
        secondary: ['arms', 'shoulders', 'core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '卷腹',
        aliases: ['仰卧起坐', 'crunch', 'sit-up'],
        type: 'strength',
        primary: ['core'],
        secondary: [],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '平板支撑',
        aliases: ['plank'],
        type: 'strength',
        primary: ['core'],
        secondary: ['shoulders'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '跑步',
        aliases: ['慢跑', 'running', 'jogging'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '游泳',
        aliases: ['swimming'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['back', 'shoulders'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '骑行',
        aliases: ['cycling', '自行车'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '跳绳',
        aliases: ['jump rope'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '篮球',
        aliases: ['打球', '打篮球', 'basketball'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '足球',
        aliases: ['踢球', '踢足球', 'football', 'soccer'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'core'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '羽毛球',
        aliases: ['打羽毛球', 'badminton'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'shoulders', 'arms'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '网球',
        aliases: ['打网球', 'tennis'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'shoulders', 'arms'],
        enabled: true,
        custom: false,
      },
      {
        exerciseName: '乒乓球',
        aliases: ['打乒乓球', 'ping pong', 'table tennis'],
        type: 'cardio',
        primary: ['cardio'],
        secondary: ['legs', 'arms'],
        enabled: true,
        custom: false,
      },
    ],
  }
}

export function defaultAthleteProfile(): AthleteProfileStore {
  return {
    version: 1,
    updatedAt: new Date().toISOString(),
    basics: {
      age: 25,
      heightCm: 170,
      bodyWeightKg: 65,
      sport: 'basketball',
      position: 'guard',
      notes: '',
    },
    preferences: {
      weeklyFrequency: 5,
      sessionLimitMinutes: 120,
      priorities: [
        'max_strength',
        'hypertrophy_weight_gain',
        'basketball_explosiveness',
        'recovery',
      ],
      antiAnxietyPrinciple: true,
    },
    benchmarks: [
      {
        id: 'bodyweight',
        exerciseName: '体重',
        kind: 'body_metric',
        currentValue: 65,
        targetMin: 70,
        targetMax: 72,
        unit: 'kg',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'squat',
        exerciseName: '深蹲',
        kind: 'strength',
        currentValue: 60,
        targetMin: 85,
        targetMax: 90,
        unit: 'kg',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'deadlift',
        exerciseName: '硬拉',
        kind: 'strength',
        currentValue: 80,
        targetMin: 105,
        targetMax: 115,
        unit: 'kg',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'bench',
        exerciseName: '卧推',
        kind: 'strength',
        currentValue: 40,
        targetMin: 55,
        targetMax: 60,
        unit: 'kg',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'ohp',
        exerciseName: '实力推',
        kind: 'strength',
        currentValue: 30,
        targetMin: 40,
        targetMax: 45,
        unit: 'kg',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'pullup_bw',
        exerciseName: '引体向上',
        kind: 'bodyweight_reps',
        currentValue: 12,
        targetMin: 16,
        targetMax: 18,
        unit: 'reps',
        targetWeeks: 26,
        note: '',
      },
      {
        id: 'pullup_weighted',
        exerciseName: '引体向上',
        kind: 'weighted_reps',
        currentValue: 0,
        targetMin: 6,
        targetMax: 6,
        unit: 'reps',
        targetWeeks: 26,
        extraWeightKg: 10,
        note: '负重10kg×6',
      },
    ],
  }
}

export function defaultProfileStore(): ProfileStore {
  return {
    version: 1,
    body: {
      heightCm: 170,
      currentWeightKg: 70,
      weightLogs: [],
    },
    goal: {
      type: 'maintain',
      targetWeightKg: null,
      targetDate: null,
    },
    avatar: {
      skinTone: 'medium',
      hairStyle: 'short',
      hairColor: '#2a1d16',
      shirtColor: '#3b82f6',
      shortsColor: '#111827',
    },
  }
}

export function defaultAchievementsStore(): AchievementsStore {
  return {
    version: 1,
    definitions: [
      {
        id: 'habit_week_3',
        type: 'habit',
        name: '每周 3 练',
        description: '自然周内完成 3 次训练',
        icon: '📅',
        condition: { kind: 'weekly_workout_count', minCount: 3 },
        enabled: true,
      },
      {
        id: 'habit_week_5',
        type: 'habit',
        name: '训练狂热者',
        description: '自然周内完成 5 次训练',
        icon: '🔥',
        condition: { kind: 'weekly_workout_count', minCount: 5 },
        enabled: true,
      },
      {
        id: 'habit_month_10',
        type: 'habit',
        name: '月度铁人',
        description: '本月累计训练 10 次',
        icon: '🏅',
        condition: { kind: 'monthly_workout_count', minCount: 10 },
        enabled: true,
      },
      {
        id: 'habit_month_20',
        type: 'habit',
        name: '月度战士',
        description: '本月累计训练 20 次',
        icon: '⚔️',
        condition: { kind: 'monthly_workout_count', minCount: 20 },
        enabled: true,
      },
      {
        id: 'habit_stable_4weeks',
        type: 'habit',
        name: '稳定输出',
        description: '连续 4 周每周至少训练 2 次',
        icon: '📈',
        condition: { kind: 'consecutive_weeks', weeks: 4, minPerWeek: 2 },
        enabled: true,
      },
      {
        id: 'habit_return',
        type: 'habit',
        name: '欢迎回来',
        description: '停训 2 周以上后恢复训练',
        icon: '🌟',
        condition: { kind: 'return_after_break', minBreakDays: 14 },
        enabled: true,
      },
      {
        id: 'habit_first_workout',
        type: 'habit',
        name: '旅程开始',
        description: '完成第一次训练',
        icon: '🚀',
        condition: { kind: 'monthly_workout_count', minCount: 1 },
        enabled: true,
      },
      {
        id: 'breakthrough_pr',
        type: 'breakthrough',
        name: '突破极限',
        description: '打破任意动作的个人重量纪录',
        icon: '💪',
        condition: { kind: 'exercise_pr' },
        enabled: true,
      },
      {
        id: 'breakthrough_1000t',
        type: 'breakthrough',
        name: '千吨俱乐部',
        description: '累计总训练重量达 1,000 吨',
        icon: '🏆',
        condition: { kind: 'total_volume_kg', minVolumeKg: 1_000_000 },
        enabled: true,
      },
      {
        id: 'breakthrough_100t',
        type: 'breakthrough',
        name: '百吨先锋',
        description: '累计总训练重量达 100 吨',
        icon: '🎯',
        condition: { kind: 'total_volume_kg', minVolumeKg: 100_000 },
        enabled: true,
      },
      {
        id: 'breakthrough_10t',
        type: 'breakthrough',
        name: '铁路起点',
        description: '累计总训练重量达 10 吨',
        icon: '⚡',
        condition: { kind: 'total_volume_kg', minVolumeKg: 10_000 },
        enabled: true,
      },
      {
        id: 'goal_lose_weight',
        type: 'goal',
        name: '减重达人',
        description: '体重达到减重目标',
        icon: '🎉',
        condition: { kind: 'weight_goal', goalType: 'lose_weight' },
        enabled: true,
      },
      {
        id: 'goal_gain_muscle',
        type: 'goal',
        name: '增肌成功',
        description: '体重达到增肌目标',
        icon: '💯',
        condition: { kind: 'weight_goal', goalType: 'gain_muscle' },
        enabled: true,
      },
    ],
    unlocked: [],
  }
}
